version: '3'

services:
    rhythm-bot-server:
        build:
            context: './'
            dockerfile: './Dockerfile'
        volumes:
            - './data:/home/rhythmbot/data'
        environment:
            STREAM_VOLUME: '0.05'
        # read in DISCORD_TOKEN from dotenv
        env_file: '.env'
